DATASET:
  root_dataset: "../bdd100k/seg"
  list_train: "../bdd100k/seg/training.odgt"
  list_val: "../bdd100k/seg/validation.odgt"
  num_class: 19
  ignore_index: 255
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "c1_deepsup"
  fc_dim: 320

TRAIN:
  batch_size_per_gpu: 3
  num_epoch: 40
  start_epoch: 20
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_40.pth"

TEST:
  checkpoint: "epoch_40.pth"
  result: "./"

BAYESIAN:
  checkpoint: "epoch_40.pth"
  start_epoch: 0
  num_epoch: 20

DIR: "ckpt/ade20k-mobilenetv2dilated-c1_deepsup-bdd100k"
